### ISSUE TITLE
Bugs when running the development server

### ISSUE THREAD

**Issue by YashKandalkar** [RashikaKarki/Related-Articles-Wikipedia#3]
**Describe the bug**
There are a few errors which pops up when running the development server after following the instructions from README.md:
1. The pip install command should have a -r option:
  `pip install -r requirements.txt`
2. When installing packages from the above command, and running the server, an import error is thrown saying that `plotly` is not found
  (This is resolved after adding `plotly` in requirements.txt)
3. The server runs with debug=False in development environment too, so maybe it'll be better to set the env var `FLASK_ENV=development` too
  We can create a .env for the 2 env  vars needed (FLASK_ENV and FLASK_APP) and then use python-dotenv which is already in requirements.txt to load the env vars from there, so that we have the debug mode on local enviroment.

Are you accepting PRs? I have added the above changes:
1. load env in main.py,
2. add -r in the readme and a step to create a .env file.
3. add plotly to requirements 
4. add .env in .gitignore

Another question: 
When a search happens, it downloads the compressed csv file and parses it on the fly, correct? The 2021-01 file is 383MB which takes a lot of time to load, is it possible to store in data in a database? I know the data is very large but can we store in maybe a nosql db like mongo which is free and has sorting, searching in it too. It has like 500MB free storage I think.
Not completely sure if it downloads the whole file, but the search takes a lot of time on my device, do tell me if I'm doing anything incorrectly!

**Comment by RashikaKarki** [comment]
@YashKandalkar  Thank you for pointing out these issues. 
Yes, I have indeed missed `-r` is the documentation and the server does run with `debug = False` in development environment. 
However, It seems like I have imported Plotly here:
https://github.com/RashikaKarki/Related-Articles-Wikipedia/blob/fa1f0b0e47780335d360cf132ce001f8924dc572/scripts/article.py#L1
but have not used it so just removing that should fix the issue. 
I would be happy to merge a PR that fixes these issues. 

And yes the performance of the whole application can definitely be improved if we could store those data in some database however my goal is to work with all the data in the dump which would end up being more than 10 GB's. So, I am still exploring ways on how I can store the data internally. One way to go about it is just storing unique article mapped with it's related articles in the database and not every single data which would save a lot of space and also can later be updated by analyzing new dump data every month.

**Comment by YashKandalkar** [comment]
@RashikaKarki Alright, I'll make a PR soon.
> One way to go about it is just storing unique article mapped with it's related articles in the database and not every single data which would save a lot of space

This sounds good, add some issues if you need any help! I'll try solving the other 2 issues till then.

**Comment by RashikaKarki** [comment]
Sounds good. Thanks
